#!/bin/sh

find "$@" -type f -printf "%s  %p\n" | while read ab; do
	sum="$(printf %8.8x "${ab%%  *}")"
	nom="${ab#*  }"
	mdsum="$(dd if="$nom" bs=512 count=1 2>/dev/null | md5sum 2>/dev/null)"
	mdsum="${mdsum%%  *}"
	sum="$sum$mdsum"
	if [ "${#sum}" != "40" ]; then
		sum="0000000000000000000000000000000000000000"
	fi
	echo "$sum  $nom"
done
